// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt1_P9gvEPDDMjg4wn1sqel4oCDxOMveQ',
    appId: '1:295881072585:web:d8ae7c48bb510217491218',
    messagingSenderId: '295881072585',
    projectId: 'matchify-337',
    authDomain: 'matchify-337.firebaseapp.com',
    storageBucket: 'matchify-337.appspot.com',
    measurementId: 'G-44BSLNGQDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9ojnG9p7AtL6uKD6RZOuSY2U_k9RRnvs',
    appId: '1:295881072585:android:d9cb313e80786acb491218',
    messagingSenderId: '295881072585',
    projectId: 'matchify-337',
    storageBucket: 'matchify-337.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIMhGcfVkYBDEV5wS2b7_qPy-8bb8hAAU',
    appId: '1:295881072585:ios:9b1a7a8aca886db1491218',
    messagingSenderId: '295881072585',
    projectId: 'matchify-337',
    storageBucket: 'matchify-337.appspot.com',
    iosClientId: '295881072585-bsemhg46c8c58iv8pqvn0nlrdep23m91.apps.googleusercontent.com',
    iosBundleId: 'com.paragraf.matchify',
  );
}
